export default {
    INVALID_CREDENTIALS: -1,
    OUTDATED_CLIENT: -2,
    USER_BANNED: -3,
    MULTIACCOUNT_DETECTED: -4,
    SERVER_ERROR: -5,
    CUTTING_EDGE_MULTIPLAYER: -6,
    ACCOUNT_PASSWORD_RESET: -7,
    VERIFICATION_REQUIRED: -8
};